MAPA_CATEGORIAS_SP = {61: 7, 62: 8, 63: 9, 64: 10}
DIAS_CONSULTA_MDFE = 180
NOME_PLANILHA_EXCEL = 'PASSAGENS PEDÁGIO'
TABELA_DESTINO_CONTESTACOES = 'contestacoes'
ESQUEMA_DESTINO_CONTESTACOES = 'dbo'

